/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TransactionsObjectPageObjectPage journey");

        opaTest("Navigate to TransactionsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCustomersListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCustomersListGenerated.onTable().iCheckRows();
            When.onTheCustomersListGenerated.onTable().iPressRow(0);

            Then.onTheCustomersObjectPageGenerated.iSeeThisPage();
            Then.onTheCustomersObjectPageGenerated.onTable({ property: "transactions" }).iCheckRows();
            When.onTheCustomersObjectPageGenerated.onTable({ property: "transactions" }).iPressRow(0);

            Then.onTheTransactionsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTransactionsObjectPageGenerated.iCheckSection({ section: "GeneralInformationFacet" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneralInformationFacet" }).iCheckField({ property: "customer_customerID" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneralInformationFacet" }).iCheckField({ property: "channel" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneralInformationFacet" }).iCheckField({ property: "amount" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneralInformationFacet" }).iCheckField({ property: "txnDate" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneralInformationFacet" }).iCheckField({ property: "pointsEarned" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});